/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 *
 * OpenAPI spec version: v0.51.1
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';

/**
 * Enthält sämtliche Informationen über einen Account. Zugriff wird nur authorisierten Benutzern gewährt.
 */
export interface AccountBalance {
    /**
     * Enthält den aktuellen Saldo des Accounts.
     */
    readonly balance: number;
    /**
     * Spezifiziert zusätzliche Informationen über den Besitzer des Accounts.
     */
    readonly owner: Account;
}