/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 *
 * OpenAPI spec version: v0.51.1
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Definiert spezifische, vertrauliche Informationen über einen Account. Zugriff wird nur authorisierten Benutzern gewährt.
 */
export interface Account { 
    /**
     * Spezifiziert den eindeutigen Login-Namen des Benutzers.
     */
    readonly login: string;
    /**
     * Definiert den Vornamen der im Account hinterlegten Person.
     */
    readonly firstname: string;
    /**
     * Definiert den Nachnamen der im Account hinterlegten Person.
     */
    readonly lastname: string;
    /**
     * Enthält die eindeutige Bankkonto-Nummer des abgerufenen Accounts.
     */
    readonly bban: string;
}