/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 *
 * OpenAPI spec version: v0.51.1
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enthält die Fehlerinformationen, welche den Server-Side Error beschreiben.
 */
export interface ErrorMessage { 
    /**
     * Beschreibt den aufgetretenen Fehler.
     */
    readonly message: string;
    /**
     * Ein optionales Objekt mit zusätzlichen Informationen zum Fehler.
     */
    readonly data?: any;
}