/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 *
 * OpenAPI spec version: v0.51.1
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Definiert ein Subset des Accounts mit der Namens-Informationen einer Person.
 */
export interface NameInfo { 
    /**
     * Definiert den Vornamen der im Account hinterlegten Person.
     */
    readonly firstname: string;
    /**
     * Definiert den Nachnamen der im Account hinterlegten Person.
     */
    readonly lastname: string;
}