/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 *
 * OpenAPI spec version: v0.51.1
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionConfirmation } from './transaction-confirmation';

/**
 * Enthält eine gefilterte Liste mit Überweisungen von Konto A nach X (target).
 */
export interface TransactionQuery { 
    readonly query: {
        /**
         * Spezifiziert die totale Anzahl der Transaktionen vor der Anwendung der Filter.
         */
        readonly resultcount: number;

        /**
         * Enthält die Anzahl der Resulte, welche zurückgegeben werden sollen.
         */
        readonly count?: number;

        /**
         * Definiert die Anzahl der übersprungenen x Resultate.
         */
        readonly skip?: number;

        /**
         * Falls in der Query spezifiziert, enthält dieses Property den Date-Filter aus startDate.
         */
        readonly startDate?: string | null;

        /**
         * Falls in der Query spezifiziert, enthält dieses Property den Date-Filter aus endDate.
         */
        readonly endDate?: string | null;
    };

    /**
     * Enthält die gefilterte Liste an Transaktionen für die Answertung/Darstellung.
     */
    readonly result: ReadonlyArray<TransactionConfirmation>;
}