/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 * 
 * OpenAPI spec version: v0.25.2
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */
import { inject, Injectable }                   from '@angular/core';
import { HttpClient }                           from '@angular/common/http';

import { Observable }                           from 'rxjs';

import { AccountBalance } from './dto/account-balance';
import { NameInfo } from './dto/name-info';
import { getOptions, getServerUrl } from './http-environment';

/**
 * Mit dem Account Service können Information zum aktuellen
 * Account sowie zu fremden Accounts abgefragt werden.
 */
@Injectable({providedIn: 'root'})
export class AccountResourceService {
  private http = inject(HttpClient);

  /**
   * Ruft erweiterte Informationen (z.B. aktuelles Saldo) über den aktuellen User vom Server ab.
   * 
   * @param jwtToken Diese Methode benötigt das JWT Token des aktuell eingeloggten Benutzers (siehe Authentication Service).
   * @example Gibt das Resultat im folgenden Format zurück:
   * ```json
   * {
   *    "balance": 1000,
   *    "owner":
   *    {
   *       "login": "bmueller",
   *       "firstname": "Bob",
   *       "lastname": "Müller",
   *       "bban": "0083 6001 0000 0000 1"
   *    }
   * }
   * ```
   */
  public getCurrentBalance(jwtToken: string): Observable<AccountBalance> {
    return this.http.get<AccountBalance>(
      getServerUrl('/accounts'),
      getOptions(jwtToken, false) );
  }

  /**
   * Ruft die Account Informationen über einen beliebigen Account via BBAN (Basic Bank Account Number) vom System ab.
   * 
   * @param jwtToken Diese Methode benötigt das JWT Token des aktuell eingeloggten Benutzers (siehe Authentication Service).
   * @param accountNumber Nummer des accounts, wessen Informationen abgefragt werden sollen.
   * @example Gibt das Resultat im folgenden Format zurück:
   * ```json
   * {
   *    "firstname": "Lisa",
   *    "lastname": "Meier"
   * }
   * ```
   */
  public getAccountInfo(jwtToken: string, accountNumber: string): Observable<NameInfo> {
    return this.http.get<NameInfo>(
      getServerUrl(`/accounts/${encodeURIComponent(accountNumber)}`),
      getOptions(jwtToken, false));
  }
}
