/**
 * BWZ-Rappi - Bank of Rapperswil Backend
 * Das Backend für die Bank of Rapperswil stellt eine vereinfachte API für das Management von Finanz-Transaktionen als Übungsplattform bereit.
 * 
 * OpenAPI spec version: v0.25.2
 * 
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */
import { inject, Injectable }                   from '@angular/core';
import { HttpClient }                           from '@angular/common/http';
 
import { catchError, Observable, tap, of }      from 'rxjs';

import { Account } from './dto/account';
import { Credential } from './dto/credential';
import { LoginInfo } from './dto/login-info';
import { RegistrationInfo } from './dto/registration-info';
import { getOptions, getServerUrl } from './http-environment';

/**
 * Mit dem Authentication Service können neue Benutzer angelegt und
 * kann in existierende Accounts eingeloggt werden.
 */
@Injectable({providedIn: 'root'})
export class AuthenticationResourceService {

    private http = inject(HttpClient);

  /**
   * Registriert einen neuen Benutzer im System und gibt den Benutzer mit der
   * generierten Account Nummer zurück. Ein neuer Benutzer erhält 1000.- CHF
   * Startguthaben vom System. Neue Accounts enthalten noch keine Transaktionen.
   * @param model Spezifiziert den Namen, sowie den Benutzernamen und das Password des neuen Users.
   * @example Gibt das Resultat im folgenden Format zurück:
   * ```json
   * {
   *    "login": "mHans",
   *    "firstname": "Hans",
   *    "lastname": "Muster",
   *    "bban": "0083 6001 0000 0000 4"
   * }
   * ```
   */
  public register(model: RegistrationInfo): Observable<Account> {
    return this.http.post<Account>(
      getServerUrl('/auth/register'),
      JSON.stringify(model),
      getOptions());
  }

  /**
   * Sucht nach dem angegebenen Login und überprüft das spezifizierte Passwort.
   * Gibt das JWT Token sowie den gefundenen Account zurück, falls der User gefunden wurde.
   * Ansonsten wird der Request mit einem Status-Code 404 beantwortet.
   * @param model Spezifiziert den Benutzernamen und das Password des Users.
   * @example Gibt das Resultat im folgenden Format zurück:
   * ```json
   * {
   *    "token": "eyJhbGci...",
   *    "owner":
   *    {
   *       "login": "bmueller",
   *       "firstname": "Bob",
   *       "lastname": "Müller",
   *       "bban": "0083 6001 0000 0000 1"
   *    }
   * }
   * ```
   */
  public login(model: LoginInfo): Observable<Credential | null> {
    return this.http.post<Credential>(
      getServerUrl('/auth/login'),
      JSON.stringify(model),
      getOptions())
        .pipe(
          tap(data => console.info(`Login succeeded, retrieved JWT token '${data.token}'.`)),
          catchError(err => {
            console.warn(`Login failed, invalid credentials or duplicated user name detected: ${err?.message}`, err.error);
            return of(null);
          })
        );
  }

  /**
   * Validiert ein Token eines Benutzer im System.
   * Gibt den HTTP Status-Code 200 zurück, falls des Token noch gültig ist und der Zugriff über das Token auf die API gewährleistet werden kann. Diese Methode benötigt das JWT Token des aktuell eingeloggten Benutzers.
   * @param jwtToken Diese Methode benötigt das JWT Token des aktuell eingeloggten Benutzers (siehe Authentication Service).
   */
  public validate(jwtToken: string): Observable<void> {
    return this.http.post<void>(
        getServerUrl('/auth/validate'),
        null,
        getOptions(jwtToken, false));
  }
}

